import React from 'react';
import { StyleSheet } from 'react-native'
import { colors } from '../../../colors';

const styles = StyleSheet.create({
    container:{

    },
    header:{
        backgroundColor:colors.blue,
        height:50,
        width:'100%',
        justifyContent:'center',
        paddingHorizontal:5
    },
    topTextContainer:{
        height:80,
        width:'100%',
        backgroundColor:colors.blue,
        paddingHorizontal:10
    },
    topMainText:{
        color:'white',
        fontSize:16,
        marginBottom:10
    },
    topSideText:{
        color:'white',
        fontSize:12
    },
    buttonContainer:{
        height:50,
        width:'100%',
        backgroundColor:colors.blue,
        flexDirection:'row',
        justifyContent:'space-between'
    },
    button:{
        borderWidth:1,
        width:110,
        height:30,
        padding:3,
        borderRadius:50,
        alignItems:'center',
        justifyContent:'center',
        backgroundColor:'black',
        marginLeft:10
    },
    buttonText:{
        fontSize:12,
        color:'white'
    },
    image:{
        height:50,
        width:50,
    },
    listContainer:{
        height:80,
    },
    textInputContainer:{
        paddingHorizontal:10,
        paddingTop:10
    },
    textInput:{
        height:40,
        paddingHorizontal:5,
        backgroundColor:colors.grey6,
        borderRadius:10,
        flexDirection:'row',
        alignItems:'center',
        justifyContent:'space-between'
    },
    locationText:{
        color:'black',
    },
    timeButton:{
        width:70,
        height:20,
        borderRadius:35,
        backgroundColor:'white',
        flexDirection:'row',
        alignItems:'center',
        justifyContent:'space-evenly'
    },
    pastLocationContainer:{
        padding:10
    },
    mapAndLocation:{
        flexDirection:'row'
    },
    pastLocation:{
        height:60,
        borderBottomWidth:1,
        flexDirection:'row',
        alignItems:'center',
        justifyContent:'space-between'
    },
    mapIconContainer:{
        height:30,
        width:30,
        backgroundColor:colors.grey6,
        justifyContent:'center',
        alignItems:'center',
        borderRadius:15,
        marginRight:15
    },
})

export default styles;